
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://liphlab.github.io/EcoNet"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""

# Google tracking id to track your visitors

google-tracking-id: "UA-35880426-4"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Jacopo Grilli"
title: "{ EcoNet - NetSci 2018 Satellite - June 2018}"
description: "Website of Living 2, satellite of ECCS 2016."
keywords: "physics | transitions | ecology"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "/img/seine-cruise-paris-france.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "EcoNet - June 2018 - Paris, NetSci 2018"
  - text: "Ecological networks: spandrels, selection, and assembly."
#  - text: "Workshop starts at 14.10, Room M (Effectenbeurszaal)"

me-img: "/img/frog.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 180

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "liphlab"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/medium_Stefano.jpg"
    date: "14.15 - 15.00"
    description: "Invited speaker: Stefano Allesina (University of Chicago, Chicago, USA)."
  - image: "/img/timeline/thebault.jpg"
    date: "14.15 - 15.00"
    description: "Invited speaker: Elisa Thebault (CNRS, Paris, France)."
  - image: "/img/timeline/neo.jpg"
    date: "14.15 - 15.00"
    description: "Invited speaker: Neo Martinez (University of Arizona and Peace Lab, USA)."


#events:
#  - image: "/img/timeline/frog.jpg"
#    date: "14.10 - 14.15"
#    description: "Introduction"
#  - image: "/img/timeline/elisa.png"
#    date: "14.15 - 15.00"
#    description: "Invited speaker: Elisa Benincà (RIVM, The Netherlands). <em>Species fluctuations sustained by a cyclic succession at the edge of chaos.</em>"
#  - image: "/img/timeline/frog.jpg"
#    date: "15.00 - 15.15"
#    description: "Els Weinan (University of Amsterdam). <em>Predicting collapsing network entities before the tipping point.</em>"
#  - image: "/img/timeline/frog.jpg"
#    date: "15.15 - 15.30"
#    description: "Kazuhiro Takemoto (Kyushu Institute of Technology, Japan). <em>Environmental change influences ecological network structure on a global scale.</em>"
#  - image: "/img/timeline/frog.jpg"
#    date: "15.30 - 15.45"
#    description: "Fabio Peruzzo (University of Leeds). <em>A method for calculating an approximate analytical solution of a stochastic ecological model in space.</em>"
#  - image: "/img/timeline/coffee.jpg"
#    date: "15.45 - 16.15"
#    description: "Coffee break"
#  - image: "/img/timeline/tans.png"
#    date: "16.15 - 17.00"
#    description: "Invited speaker: Sander Tans (AMOLF, The Netherlands). <em>Tradeoffs and optimality in the evolution of gene regulation.</em>"
#  - image: "/img/timeline/stefano.png"
#    date: "17.00 - 17.45"
#    description: "Invited Speaker: Stefano Vassanelli (University of Padua). <em>Investigating the collective behaviour of neurons in the brain: what can we do and what we cannot do.</em>"
#  - image: "/img/timeline/frog.jpg"
#    date: "17.45 - 18.00"
#    description: "Charles de Santana (University of Zurich). <em>Robustness of tissue structure to perturbations in mechanical forces.</em>"

# First image of the Timeline

timeline-img: "/img/timeline/frog.jpg"


###########
# Contact #
###########

email: "liph.unipd@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
#author_blurb: ""
#author_blurb_image: ""

##################
# Social Buttons #
##################

social:
  - title: "twitter"
    url: "https://twitter.com/LIPh_Lab"

############
# 404 page #
############

404-img: "/img/frog.jpg"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  News: 'latest-post'
  Program: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
